baseURL = "https://web.northeastern.edu/hkn/"
languageCode = "en-us"
title = "NEU HKN"

theme = "minimal"
disqusShortname = "" # delete this to disable disqus comments
googleAnalytics = ""

[markup.goldmark.renderer]
unsafe= true

[params]
    author = "Matan Silver, Korina Pluss"
    description = "We are the Gamma Beta Chapter of Eta Kappa Nu, HKN, at Northeastern University."
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    #highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/eboard"
    name = "E-Board"
    weight = 4

[[menu.main]]
    url = "/tutoring"
    name = "Tutoring"
    weight = 5


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

# [[menu.icon]]
#     url = "mailto:me@example.com"
#     name = "envelope-o"
#     weight = 1
#
# [[menu.icon]]
#     url = "https://github.com/username/"
#     name = "github"
#     weight = 2
#
# [[menu.icon]]
#     url = "https://twitter.com/username/"
#     name = "twitter"
#     weight = 3
#
# [[menu.icon]]
#     url = "https://www.linkedin.com/in/username/"
#     name = "linkedin"
#     weight = 4
#
# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 5
